// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtbhfovMXw_aBCLxRsYTmYI5Vu-c8HBQ8',
    appId: '1:204616320833:web:3c2b368c80ec09eab943c0',
    messagingSenderId: '204616320833',
    projectId: 'todoyes',
    authDomain: 'todoyes.firebaseapp.com',
    storageBucket: 'todoyes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXWAY0qjBhjb-44O2c-5dRlGe1djcimkk',
    appId: '1:204616320833:android:ad3b51c069db6b11b943c0',
    messagingSenderId: '204616320833',
    projectId: 'todoyes',
    storageBucket: 'todoyes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgbhYg7-Knqq4MNJywjxPOTcCpvbtadD0',
    appId: '1:204616320833:ios:9004aa5a2316919ab943c0',
    messagingSenderId: '204616320833',
    projectId: 'todoyes',
    storageBucket: 'todoyes.appspot.com',
    iosClientId: '204616320833-l3qengvmkrofbgoigrv34ljhal24gu5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgbhYg7-Knqq4MNJywjxPOTcCpvbtadD0',
    appId: '1:204616320833:ios:9f7d436993e4437eb943c0',
    messagingSenderId: '204616320833',
    projectId: 'todoyes',
    storageBucket: 'todoyes.appspot.com',
    iosClientId: '204616320833-27ip4o1e68k9t943krbs90bb3rokqv5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp.RunnerTests',
  );
}
